// © 2024 Jar of Sparks, All Rights Reserved

#pragma once

namespace SparksEnvironmentLightingPresetPropertyNames
{
	const TSet<FName> AllPresetProperties({
		// DirectionalLight
		FName(TEXT("AtmosphereSunDiskColorScale")),
		FName(TEXT("BloomMaxBrightness")),
		FName(TEXT("BloomScale")),
		FName(TEXT("BloomThreshold")),
		FName(TEXT("BloomTint")),
		FName(TEXT("CloudScatteredLuminanceScale")),
		FName(TEXT("CloudShadowDepthBias")),
		FName(TEXT("CloudShadowExtent")),
		FName(TEXT("CloudShadowMapResolutionScale")),
		FName(TEXT("CloudShadowOnAtmosphereStrength")),
		FName(TEXT("CloudShadowOnSurfaceStrength")),
		FName(TEXT("CloudShadowRaySampleCountScale")),
		FName(TEXT("CloudShadowStrength")),
		FName(TEXT("IESBrightnessScale")),
		FName(TEXT("IndirectLightingIntensity")),
		FName(TEXT("Intensity")),
		FName(TEXT("LightColor")),
		FName(TEXT("LightSourceAngle")),
		FName(TEXT("LightSourceSoftAngle")),
		FName(TEXT("OcclusionMaskDarkness")),
		FName(TEXT("RelativeRotation")),
		FName(TEXT("ShadowSourceAngleFactor")),
		FName(TEXT("SpecularScale")),
		FName(TEXT("Temperature")),
		FName(TEXT("TraceDistance")),
		FName(TEXT("VolumetricScatteringIntensity")),
		FName(TEXT("bEnableLightShaftBloom")),
		FName(TEXT("bEnableLightShaftOcclusion")),

		// ExponentialHeightFog
		FName(TEXT("DirectionalInscatteringExponent")),
		FName(TEXT("DirectionalInscatteringLuminance")),
		FName(TEXT("DirectionalInscatteringStartDistance")),
		FName(TEXT("FogCutoffDistance")),
		FName(TEXT("FogDensity")),
		FName(TEXT("FogHeightFalloff")),
		FName(TEXT("FogHeightOffset")),
		FName(TEXT("Fog Height Offset")),
		FName(TEXT("FogInscatteringLuminance")),
		FName(TEXT("FogMaxOpacity")),
		FName(TEXT("FullyDirectionalInscatteringColorDistance")),
		FName(TEXT("InscatteringTextureTint")),
		FName(TEXT("NonDirectionalInscatteringColorDistance")),
		FName(TEXT("SecondFogData")),
		FName(TEXT("SkyAtmosphereAmbientContributionColorScale")),
		FName(TEXT("StartDistance")),
		FName(TEXT("VolumetricFogAlbedo")),
		FName(TEXT("VolumetricFogDistance")),
		FName(TEXT("VolumetricFogExtinctionScale")),
		FName(TEXT("VolumetricFogNearFadeInDistance")),
		FName(TEXT("VolumetricFogScatteringDistribution")),
		FName(TEXT("VolumetricFogStartDistance")),
		FName(TEXT("VolumetricFogStaticLightingScatteringIntensity")),
		FName(TEXT("bEnableVolumetricFog")),

		// SkyAtmosphere
		FName(TEXT("AerialPerspectiveStartDepth")),
		FName(TEXT("AerialPespectiveViewDistanceScale")),
		FName(TEXT("AtmosphereHeight")),
		FName(TEXT("BottomRadius")),
		FName(TEXT("GroundAlbedo")),
		FName(TEXT("HeightFogContribution")),
		FName(TEXT("MieAbsorption")),
		FName(TEXT("MieAbsorptionScale")),
		FName(TEXT("MieAnisotropy")),
		FName(TEXT("MieExponentialDistribution")),
		FName(TEXT("MieScattering")),
		FName(TEXT("MieScatteringScale")),
		FName(TEXT("MultiScatteringFactor")),
		FName(TEXT("OtherAbsorption")),
		FName(TEXT("OtherAbsorptionScale")),
		FName(TEXT("RayleighExponentialDistribution")),
		FName(TEXT("RayleighScattering")),
		FName(TEXT("RayleighScatteringScale")),
		FName(TEXT("SkyLuminanceFactor")),
		FName(TEXT("TransmittanceMinLightElevationAngle")),
		FName(TEXT("Absorption Scale")),
		FName(TEXT("Absorption")),

		// SkyLight
		FName(TEXT("CloudAmbientOcclusionExtent")),
		FName(TEXT("Contrast")),
		FName(TEXT("IndirectLightingIntensity")),
		FName(TEXT("Intensity")),
		FName(TEXT("LightColor")),
		FName(TEXT("LowerHemisphereColor")),
		FName(TEXT("MinOcclusion")),
		FName(TEXT("OcclusionExponent")),
		FName(TEXT("OcclusionMaxDistance")),
		FName(TEXT("OcclusionTint")),
		FName(TEXT("SkyDistanceThreshold")),
		FName(TEXT("VolumetricScatteringIntensity")),
		FName(TEXT("bCloudAmbientOcclusion")),
		FName(TEXT("bRealTimeCapture")),

		// VolumetricClouds
		FName(TEXT("AerialPespectiveMieScatteringFadeDistance")),
		FName(TEXT("AerialPespectiveMieScatteringStartDistance")),
		FName(TEXT("AerialPespectiveRayleighScatteringFadeDistance")),
		FName(TEXT("AerialPespectiveRayleighScatteringStartDistance")),
		FName(TEXT("GroundAlbedo")),
		FName(TEXT("LayerBottomAltitude")),
		FName(TEXT("LayerHeight")),
		FName(TEXT("TracingStartMaxDistance"))
	});
}